kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: descheduler
subjects:
- kind: ServiceAccount
  name: descheduler
  namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: descheduler
  apiGroup: rbac.authorization.k8s.io
