
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: descheduler
  namespace: ${namespace}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: descheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
    spec:
      template:
        spec:
          serviceAccountName: descheduler
          containers:
          - name: descheduler
            image: "komljen/descheduler:v0.7.0"
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
            - /bin/descheduler
            - --policy-config-file=/policy-dir/policy.yaml
            - --v=4
            - --max-pods-to-evict-per-node=10
          restartPolicy: "OnFailure"
          volumes:
          - name: policy-volume
            configMap:
              name: descheduler-policy
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nodetype
                    operator: In
                    values: ["system"]
          tolerations:
          - key: node-role.kubernetes.io/system
            operator: Exists
