apiVersion: v1
kind: Service
metadata:
  name: kiam-server
  namespace: ${namespace}
spec:
  clusterIP: None
  selector:
    app: kiam
    role: server
  ports:
  - name: grpclb
    port: 8443
    targetPort: 8443
    protocol: TCP
