apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: ${namespace}
  labels:
    app: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
      annotations:
        iam.amazonaws.com/role: ${role_name}
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.8
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=${domain} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-owner-id=${name}
        - --namespace=${namespace}
        resources:
          requests:
            cpu: 1m
            memory: 16Mi
          limits:
            cpu: 10m
            memory: 32Mi

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values: ["system"]
      tolerations:
      - key: node-role.kubernetes.io/system
        operator: Exists
