kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iam-roller
  namespace: ${namespace}
subjects:
- kind: ServiceAccount
  name: iam-roller
  namespace: ${namespace}
roleRef:
  kind: Role
  name: iam-roller
  apiGroup: rbac.authorization.k8s.io
